### ISSUE TITLE
Publish v4.4.0 

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-ie8#88]
This issue is to track progress of publishing v4.4.0

**Changelog**

- Added responsive container classes
- Improved layout with `clear: both`  added to .row, .container, .container-fluid, header, main, footer.
- Minified versions of CSS and JS included

**TODO**

- [ ] Update version numbers in CSS, JS and package.json
- [ ] Add minified versions
- [ ] Publish to NPM
- [ ] Publish to Packagist for Composer
